<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegisterType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    /**
     * Méthode permettant d'enregistrer un utilisateur
     * @Route("/Inscription", name="user_register")
     */
    public function register(EntityManagerInterface $em, UserRepository $ur, Request $request, UserPasswordEncoderInterface $encoder)
    {
        $user = new User();
        $registerForm = $this->createForm(RegisterType::class, $user);
        $user->setDateCreated(new \DateTime());
        $user->setRoles(['ROLE_USER']);

        $registerForm->handleRequest($request);
        if($registerForm->isValid() && $registerForm->isSubmitted()){
            //Hasher le password
            $hashed = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hashed);

            $photo = $registerForm->get('photo')->getData();
            if($photo){
                $photoName = $this->generateUniqueFileName() . '.' . strtolower($photo->getClientOriginalExtension());
                $photo->move(
                  $this->getParameter('upload_photos_profile'),
                  $photoName
                );
                $user->setPhoto($photoName);
            }else{
                $user->setPhoto('default_profile_pic_fixtures.png');
            }

            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('/');
        }
        return $this->render('user/index.html.twig', [
            "registerForm" => $registerForm->createView(),
        ]);
    }

    /**
     * Méthode permettant de renvoyer un nom unique pour la photo de profil
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
